name = "Strings"
grammar = "property_list"
brackets = [
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "/* ", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
autoclose_before = ";"
line_comments = ["// "]
block_comment = { start = "/*", prefix="", end = "*/", tab_size = 2 }
path_suffixes = ["strings"]
